[package]
name = "abi_stable_ext"
version = "0.1.0"
authors = ["Alex Franchuk <afranchuk@caci.com>"]
edition = "2018"

[dependencies]
abi_stable = "0.9"
bytes = "0.5"
futures = { version = "0.3", features = ["thread-pool"] }
pin-project = "1"
uuid = { version = "0.8", features = ["serde", "v5"] }
