[package]
name = "abi_stable_ext"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
abi_stable.workspace = true
bytes = "0.5"
futures.workspace = true
log.workspace = true
pin-project.workspace = true
uuid = { version = "0.8", features = ["serde", "v5"] }
