[package]
name = "bob"
version = "1.0.0-alpha.0"
authors = ["Alex Franchuk <afranchuk@caci.com>"]
edition = "2018"

[dependencies]
atty = "^0.2"
chrono = "^0.4"
grease = { path = "../grease" }
log = "^0.4"
rand = "^0.7"
simplelog = "^0.7"
tack = { path = "../tack" }
term = "^0.6"
uuid = "^0.7"

