[package]
name = "ergo_script"
version = "1.0.0-rc.0"
authors = ["Alex Franchuk <afranchuk@caci.com>"]
edition = "2021"

[dependencies]
ergo_runtime = { path = "../ergo_runtime" }
futures = "^0.3"
libloading = "^0.6"
log = "^0.4"
plugin_tls = { version = "0.3", features = ["host"] }
