[package]
name = "ergo_runtime"
version = "1.0.0-beta.3"
authors = ["Alex Franchuk <afranchuk@caci.com>"]
edition = "2018"

[dependencies]
abi_stable = "0.8"
bincode = "^1.2"
ergo_runtime_macro = { path = "../ergo_runtime_macro" }
futures = "^0.3"
grease = { path = "../grease" }
log = "^0.4"
uuid = { version = "0.8", features = ["v5"] }
