[package]
name = "so_runtime"
version = "1.0.0-alpha.4"
authors = ["Alex Franchuk <afranchuk@caci.com>"]
edition = "2018"

[dependencies]
abi_stable = "0.8"
futures = "^0.3"
grease = { path = "../grease" }
so_runtime_macro = { path = "../so_runtime_macro" }
