[package]
name = "grease"
version = "0.2.0"
authors = ["Alex Franchuk <afranchuk@caci.com>"]
edition = "2018"

[dependencies]
fasthash = "0.4"
futures = { version = "0.3", features = ["thread-pool"] }
grease_macro = { path = "../grease_macro" }
lazy_static = "^1"
log = "^0.4"
num_cpus = "^1"
parking_lot = "^0.10"
proc-macro-hack = "0.5"
uuid = { version = "0.8", features = ["serde", "v5"] }
