[package]
name = "grease"
version = "0.1.0"
authors = ["Alex Franchuk <afranchuk@caci.com>"]
edition = "2018"

[dependencies]
futures-preview = "=0.3.0-alpha.19"
lazy_static = "^1"
log = "^0.4"
num_cpus = "^1"
uuid = { version = "0.7", features = ["v5"] }
