ARG TAG
FROM debian:$TAG

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

ARG TARGETARCH
ARG TARGETVARIANT
COPY ergo-${TARGETARCH}${TARGETVARIANT}.run /installer

RUN apt-get update && apt-get install less && rm -rf /var/lib/apt/lists/* \
  && sh /installer install /usr && rm /installer
