ARG TAG
FROM alpine:$TAG

ARG TARGETARCH
ARG TARGETVARIANT
COPY ergo-${TARGETARCH}${TARGETVARIANT}.run /installer

RUN apk add libgcc ncurses-terminfo-base \
  && sh /installer install /usr/local && rm /installer
