[package]
name = "grease_macro"
version = "0.4.0"
authors = ["Alex Franchuk <afranchuk@caci.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full"] }
