[package]
name = "grease_macro"
version = "0.1.0"
authors = ["Alex Franchuk <afranchuk@caci.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro-hack = "0.5"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
