[book]
authors = ["Alex Franchuk"]
language = "en"
multilingual = false
src = "src"
title = "Ergo"

[output.html]
additional-js = ["ergo.js"]
additional-css = ["style.css"]

[output.html.fold]
enable = true
