[package]
name = "ergo_runtime_macro"
version = "1.0.0-beta.3"
authors = ["Alex Franchuk <afranchuk@caci.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
